### ISSUE TITLE
Need for standardized sensor data not on loggers

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/data-workflows#157] opened 2024-04-29 23:42 UTC
This is relevant to our community fund idea, but we should make sure non-logger sensor data can be processed to a similar format + level as our campbell sensor data

**Comment by stephpenn1** [comment] 2024-04-29 23:42
This question came up from YSI data from @amyerspigg

**Comment by bpbond** [comment] 2024-04-30 10:29
Thanks. Just to clarify, does this mean we want non-logger data as part of L1, not just L2?

**Comment by bpbond** [comment] 2024-10-27 09:42
Dupe of #213

**Closed** 2024-10-27 09:43 UTC
